### ISSUE TITLE
Consensus

### ISSUE THREAD

**Issue by alpreu** [toniSta/blockchain_vaccination_records#9]
This issue describes what need to be done to make judgements work

# General notes:

- A block is discarded from a chain if the host received more than half the number of admissions denying the block at this point of the chain
 - Each admission will send judgements over the received blocks. Each block gets an `accept`, if the block matches more appropriate at any point of the chain (e.g. it was created by a older admission node at this point of the index). 
A admission can change an `accept` to `deny` if it receives a more suitable block for that positions (in this case the new block gets an `accept` and the `accept` of the old block (and every following block) is changed to `deny`
 - Until a block gets enough `deny`s there could be more than one chain branch. the chain is therefore saved as a tree structure. (since every admission node will just `accept` one tree at a time, it will converge towards a tree with 1 child per tree-node)

# TODOs (the list is probably not extensive. Feel free to add ToDos)

- [x] block creation should check to generate a block for each leaf of the tree (PR #42)
- [x] Blocks needs to be saved to disk with following filenames: `<index of the block>_<hash of the parent>_<own hash>` and we need to reconstruct the tree structur from these files (implemented in PR #40)
- [x] receive block methods needs to remove contained transaction from its own queue (implemented in branch tree_structure PR #42)
- [x] judgements: create judgement object (implemented in PR #41) 
- [x] full_client: send judgement: broadcast the judgements(implemented in PR #41)
- [x] full-client: receive judgement: save judgement, check if we can delete a tree branch (wip PR #41)
- [x] chain: admissions_at_hash: who was a admission at the block with `hash` (including the transactions in this block) (PR #42)
- [x] chain: history_at_hash: what are the oldest admission (descending) at block with `hash`. Again including the block with `hash` (PR #42)
- [x] full_client: sync: sync the tree with neighbors (keep in mind there may be new branches yet unknown to you. We also need to send the judgements with the block, as the node that gets synchronized would miss out on all the judgements otherwise)
- [x] chain: admissions: return the admission list for each leaf of the tree with the following structure: `[(last_hash, [history of admissions descending]), (...), ...]` (PR #42)
- [x] chain: remove_tree_at_hash: remove the complete sub-tree including the node with `hash`  (implemented in branch tree_structure PR #42)
- [x] chain: get_tree_list_at_hash: get a list of all blocks in the sub-tree with `hash` as root (needed to change judgements to `deny`)  (implemented in branch tree_structure PR #42)
- [x] chain: add_block: Add block in the tree if possible or add it to dangling blocks.  (PR #41)
- [x] chain: replace list data structure with tree structure  (implemented in branch tree_structure, WIP, contains bugs) (PR #42)
- [x] print the chain tree (for demo)  (implemented in branch tree_structure, demo in `main.py`)
Inline 

- [x] inline ToDos
full-client process_dangling_blocks needs to adjust to chain 

- [x] full-client process_dangling_blocks needs to adjust to chain tree (PR #41)

- [x] #44 

# Optional (not directly needed by demo)

- [ ] Don't save complete block in the chain tree. just frequently used informations (like hash, timestamp, index). Additional infos are read from disk if needed
- [ ] Minimize tree node content. Just safe blockindex and hash of block. every other information needed is loaded from the disk (that shouldn't occure frequently). Therefore we have space to save the cahces within each tree node (dynamically created - not written to disk)

- [ ] Don't hold the complete tree in RAM. Just from the point where we have the first node with multiple children. older parts are loadad as needed.

# Raw-Notes:
![1](https://user-images.githubusercontent.com/5672310/35581419-05e6eab6-05ec-11e8-8540-05576060f227.jpg)
![2](https://user-images.githubusercontent.com/5672310/35581420-060520da-05ec-11e8-9901-2dda4768eab4.jpg)
![3](https://user-images.githubusercontent.com/5672310/35581422-061e9e5c-05ec-11e8-82c1-0f851ace73a4.jpg)
